version: '3.8'

services:
  luotianyi-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - neo4j
      - chroma

  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE

volumes:
  neo4j_data:
  chroma_data:
