# Agent-LuoTianyi 配置文件

# ===== 大模型配置 =====
llm:
  provider: "siliconflow"  # 大模型提供商
  model: "internlm/internlm2_5-7b-chat"   # 使用的模型名称
  api_key: "${SILICONFLOW_API_KEY}"  # API密钥，从环境变量读取
  base_url: "https://api.siliconflow.cn/v1"  # API基础URL
  temperature: 0.7         # 生成温度
  max_tokens: 1000         # 最大token数
  top_p: 0.9              # nucleus sampling参数

# ===== 知识库配置 =====
knowledge:
  # 向量数据库配置
  vector_store:
    type: "chroma"         # 向量数据库类型：chroma/pinecone/faiss
    persist_directory: "./data/embeddings"  # 持久化目录
    collection_name: "luotianyi_knowledge"  # 集合名称
  
  # 图数据库配置（可选）
  graph_store:
    type: "neo4j"          # 图数据库类型：neo4j/arangodb
    uri: "bolt://localhost:7687"
    username: "neo4j"
    password: "password"
  
  # 嵌入模型配置
  embedding:
    model: "text-embedding-3-small"  # 嵌入模型
    batch_size: 32         # 批处理大小
    max_length: 512        # 最大文本长度

# ===== Agent配置 =====
agent:
  persona_file: "config/persona.yaml"  # 人设配置文件
  memory:
    type: "buffer"         # 记忆类型：buffer/summary/kg
    size: 10              # 记忆窗口大小
  response:
    max_tokens: 500       # 回复最大长度
    stream: true          # 是否流式输出
  retrieval:
    top_k: 5              # 检索文档数量
    similarity_threshold: 0.7  # 相似度阈值

prompt:
  template_dir: "prompts"  # 模板目录

conversation:
  memory_type: "buffer"    # 对话记忆类型：buffer/summary/kg
  memory:                  # 对话记忆配置
    size: 10               # 记忆窗口大小
    summary_length: 200    # 摘要长度（仅在summary模式下有效）

# ===== 多模态配置 =====
multimodal:
  # TTS配置
  tts:
    enabled: false        # 是否启用TTS
    engine: "gptsovits"   # TTS引擎
    model_path: "./models/luotianyi_voice"  # 音色模型路径
  
  # Live2D配置
  live2d:
    enabled: false        # 是否启用Live2D
    model_path: "./models/luotianyi_live2d"  # Live2D模型路径
    actions:
      happy: "motion_happy.mtn"
      sad: "motion_sad.mtn"
      surprised: "motion_surprised.mtn"

# ===== 服务配置 =====
server:
  host: "0.0.0.0"        # 服务主机
  port: 8000             # 服务端口
  workers: 1             # 工作进程数
  cors_origins: ["*"]    # CORS允许的源

# ===== 日志配置 =====
logging:
  level: "INFO"          # 日志级别：DEBUG/INFO/WARNING/ERROR
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
  file: "./logs/agent.log"  # 日志文件路径
  rotation: "100 MB"     # 日志轮转大小
  retention: "30 days"   # 日志保留时间

# ===== 开发配置 =====
development:
  debug: false           # 调试模式
  reload: false          # 自动重载
  profile: false         # 性能分析
